name: Windows 

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: windows-2019
    env:
      CONTRIB_PATH: C:\Trunk2016\Contribs
      SOLUTION_PATH: C:\Trunk2016\Client_2016.sln
      BOOST_SRC: C:\Trunk2016\Contribs\boost_1_56_0
      OPENSSL_SRC: C:\Trunk2016\Contribs\openssl
      OPENSSL_OUT: C:\Trunk2016\openssl
      SDL2_PATH: C:\Trunk2016\Contribs\SDL2
      LIBCURL_PATH: C:\Trunk2016\Contribs\windows\x86\curl\curl-7.43.0
    steps:
      - name: fuck you git
        run: git config --system core.longpaths true
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create C:\Trunk2016 junction (symlink)
        shell: cmd
        run: |
          if exist C:\Trunk2016 rmdir /s /q C:\Trunk2016
          mklink /J C:\Trunk2016 "%GITHUB_WORKSPACE%"

      - name: Set CONTRIB_PATH env var
        run: |
          echo CONTRIB_PATH=C:\Trunk2016\Contribs>> %GITHUB_ENV

      - name: Cache contribs dependencies
        uses: actions/cache@v4
        with:
          path: |
            C:\Trunk2016\Contribs
            C:\Trunk2016\openssl
          key: contribs-${{ hashFiles('**/Contribs/**', '**/openssl/**') }}

      - name: Ensure OpenSSL binaries are present
        if: steps.cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Strawberry\perl\bin
          cd /d %OPENSSL_SRC%
          perl Configure VC-WIN32
          ms\32all.bat
          if not exist %OPENSSL_OUT% mkdir %OPENSSL_OUT%
          copy /Y Contribs\openssl\out32dll\ssleay32.dll %OPENSSL_OUT%
          copy /Y Contribs\openssl\out32dll\libeay32.dll %OPENSSL_OUT%

      - name: Bootstrap & Build Boost
        shell: cmd
        run: |
          cd /d %BOOST_SRC%
          if exist b2.exe (echo Boost already built) else (
            call bootstrap.bat
            call build_boost.bat
          )

      - name: Build SDL2 as DLL
        shell: pwsh
        run: |
          # Patch SDL2 project to build as DLL
          $sln = "${env:SDL2_PATH}\VisualC\SDL\SDL.vcxproj"
          (Get-Content $sln) -replace '<ConfigurationType>StaticLibrary</ConfigurationType>', '<ConfigurationType>DynamicLibrary</ConfigurationType>' |
            Set-Content $sln
          (Get-Content $sln) -replace '<TargetExtension>.lib</TargetExtension>', '<TargetExtension>.dll</TargetExtension>' |
            Set-Content $sln
          # Remove HAVE_LIBC preprocessor
          (Get-Content $sln) -replace 'HAVE_LIBC;', '' | Set-Content $sln
          # Build
          & "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_xp
          msbuild $sln /p:Configuration=Release /p:Platform=Win32

      - name: Build libcurl as Static Library
        shell: pwsh
        run: |
          $libcurl = "${env:LIBCURL_PATH}\projects\Windows\VC11\lib\libcurl.vcxproj"
          (Get-Content $libcurl) -replace '<ConfigurationType>DynamicLibrary</ConfigurationType>', '<ConfigurationType>StaticLibrary</ConfigurationType>' |
            Set-Content $libcurl
          (Get-Content $libcurl) -replace '<TargetExtension>.dll</TargetExtension>', '<TargetExtension>.lib</TargetExtension>' |
            Set-Content $libcurl
          & "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_xp
          msbuild $libcurl /p:Configuration=Release /p:Platform=Win32

      - name: Build contrib libraries (deps for main projects)
        shell: cmd
        run: |
          setlocal
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_xp
          msbuild "%SOLUTION_PATH%" /t:boost.static;zlib;libcurl;SDL2;soapcpp2;wsdl2h;ShaderCompiler;LibOVR;qtnribbon;sgCore;CoreScriptConverter2 /p:Configuration=Release /p:Platform=Win32 /m

      - name: Build RobloxStudio (ReleaseStudio)
        shell: cmd
        run: |
          setlocal
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_xp
          msbuild "%SOLUTION_PATH%" /t:RobloxStudio /p:Configuration=ReleaseStudio /p:Platform=Win32 /m

      - name: Build RCCService (ReleaseRcc)
        shell: cmd
        run: |
          setlocal
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_xp
          msbuild "%SOLUTION_PATH%" /t:RCCService /p:Configuration=ReleaseRcc /p:Platform=Win32 /m

      - name: Build WindowsClient (Release)
        shell: cmd
        run: |
          setlocal
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_xp
          msbuild "%SOLUTION_PATH%" /t:WindowsClient /p:Configuration=Release /p:Platform=Win32 /m

      - name: Upload RobloxStudio artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobloxStudio
          path: |
            C:\Trunk2016\RobloxStudio\bin\ReleaseStudio\*

      - name: Upload RCCService artifact
        uses: actions/upload-artifact@v4
        with:
          name: RCCService
          path: |
            C:\Trunk2016\RCCService\bin\ReleaseRcc\*

      - name: Upload WindowsClient artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsClient
          path: |
            C:\Trunk2016\WindowsClient\bin\Release\*
