#pragma once

namespace RBX {

	enum PartMaterial {
		/* Special */
		PLASTIC_MATERIAL = 0,
		SMOOTH_PLASTIC_MATERIAL = 1,
		NEON_MATERIAL = 2,

		/* Wood */
		WOOD_MATERIAL = 10,
		WOODPLANKS_MATERIAL = 11,

		/* Stones */
		BASALT_MATERIAL = 20,
		COBBLESTONE_MATERIAL = 21,
		CRACKED_LAVA_MATERIAL = 22,
		GRANITE_MATERIAL = 23,
		LIMESTONE_MATERIAL = 24,
		PEBBLE_MATERIAL = 25,
		ROCK_MATERIAL = 26,
		SALT_MATERIAL = 27,
		SANDSTONE_MATERIAL = 28,
		SLATE_MATERIAL = 29,

		/* Stones */
		ASPHALT_MATERIAL = 30,
		BRICK_MATERIAL = 31,
		CERAMIC_TILES_MATERIAL = 32,
		CLAY_ROOF_TILES_MATERIAL = 33,
		CONCRETE_MATERIAL = 34,
		MARBLE_MATERIAL = 35,
		PAVEMENT_MATERIAL = 36,
		PLASTER_MATERIAL = 37,
		ROOF_SHINGLES_MATERIAL = 38,

		/* Metals */
		DIAMONDPLATE_MATERIAL = 40,
		FOIL_MATERIAL = 41,
		METAL_MATERIAL = 42,
		RUST_MATERIAL = 43,

		/* Natural */
		CARDBOARD_MATERIAL = 50,
		CARPET_MATERIAL = 51,
		FABRIC_MATERIAL = 52,
		GRASS_MATERIAL = 53,
		GROUND_MATERIAL = 54,
		LEAFY_GRASS_MATERIAL = 55,
		LEATHER_MATERIAL = 56,
		MUD_MATERIAL = 57,
		RUBBER_MATERIAL = 58,
		SAND_MATERIAL = 59,

		/* Ice | 0x06XX */
		GLACIER_MATERIAL = 60,
		ICE_MATERIAL = 61,
		SNOW_MATERIAL = 62,

		/* Do not use */
		AIR_MATERIAL = 253,
		WATER_MATERIAL = 254,
		LEGACY_MATERIAL = 255, // should not be serialized
	};

	enum AlphaMode {
		TRANSPARENCY,
		OVERLAY,
		TINT,
	};

	enum ResamplingMode {
		CLOSEST,
		LINEAR,
		CUBIC,
	};

	enum TilingMode {
		REGULAR,
		ORGANIC,
		ROTATED_ORGANIC,
	};

}
